name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build
      run: bash install.sh -xe

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: w4sh
        path: build/w4sh
        retention-days: 5

   
    
